### PR TITLE
Add "wait" option to prevent more than MAX_CONNS being created at the same time

### LINKED ISSUE #45: MAX_CONNS not being respected
Hello, I'm make some experimentations running django 3 under gevent.

I've created an endpoint that execute a `pg_sleep` faking slow queries, then, I used vegeta for tests my setup with high load. 

my MAX_CONNS was 10.

But some of my api response was 500 :
```
Traceback (most recent call last):
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/danilo/Code/django_db__pool_issues_example/app/sleep_db.py", line 9, in sleep_in_db
    with connection.cursor() as cursor:
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/db/backends/base/base.py", line 260, in cursor
    return self._cursor()
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/db/backends/base/base.py", line 236, in _cursor
    self.ensure_connection()
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django_db_geventpool/backends/postgresql_psycopg2/base.py", line 49, in get_new_connection
    self.connection = self.pool.get()
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django_db_geventpool/backends/postgresql_psycopg2/psycopg2_pool.py", line 48, in get
    conn = self.create_connection()
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/django_db_geventpool/backends/postgresql_psycopg2/psycopg2_pool.py", line 84, in create_connection
    conn = self.connect(*self.args, **self.kwargs)
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
  File "/home/danilo/.local/share/virtualenvs/django_db__pool_issues_example-SoJGTr3V/lib/python3.6/site-packages/psycogreen/gevent.py", line 32, in gevent_wait_callback
    state = conn.poll()
django.db.utils.OperationalError: FATAL:  sorry, too many clients already
```

I've uploaded a project to show it.
https://github.com/dnp1/django_db_gevent_pool_issues_example

My attack was:
echo "GET http://localhost:8000/sleep_in_db" | vegeta attack -duration=10s --rate 100 | tee results.bin | vegeta report

When I watched the database:
`SELECT * FROM "pg_stat_activity" WHERE "client_addr" = '172.26.0.1'` there was 99 connections of my application.

I'm using python 3.6.10 (CPython) under Linux.
My postgres is running inside a docker container

### PR DESCRIPTION
**Pull request by bellini666**
Fix #45

### CODE REVIEW

**Comment by joekohlsdorf** [comment]
I disagree with the proposed change.

There is one person needing MAX_CONNS to be unlimited and this change should never have gotten merged in the first place. We should just revert the change and make the configuration option do what it is meant to do.
That one person can just set MAX_CONNS to INT_MAX instead. For everyone else a bug was introduced.

**Comment by bellini666** [comment]
@joekohlsdorf i don't disagree with you. I proposed the change like this because it was the way it was working in the current version, but if we want to keep the "unlimited max conns" feature we can keep and and change it to not be the default.

I can see why that user did that: He is just interested in connection reuse and not in limiting connections. I don't know how many people have use cases like that (I personally don't have any)

**Comment by bellini666** [comment]
@joekohlsdorf I thought about what you said, and you are right! The behaviour that was introduced should never have been merged in the first place.

I changed my PR to go back to the previous option and also I added something else: You can now define how many connections to reuse. Why I did that? I started to see some very high memory usage in my deployment because some connections would never be closed and would stay leaking memory (because of in-memory cache results) forever.

Now there's an option to define how many connections to reuse and everything higher than that will get closed. If 0 is defined we create the queue with one position just so we can wait in `pool.get` when maxconns was reached.

What do you think?

**Comment by jneight** [comment]
Hi!, thanks for the PR, I think this approach is much better and the current one should never got accepted, my bad.

I don't work with gevent anymore, so, if both of you agree I will merge this PR and release a new version.

**Comment by bellini666** [comment]
@jneight oh I see. Np!

Well, this change is working fine for me (using it at production already). Let's see what @joekohlsdorf thinks of the change as well :)

**Comment by anderspetersson** [comment]
Please merge this

**Comment by anderspetersson** [comment]
Thank you @jneight , is it possible to also cut a new release? Helps speed up deployments.

**Comment by jneight** [comment]
> Thank you @jneight , is it possible to also cut a new release? Helps speed up deployments.

done! :)

**Pull request merged**
